<?xml version="1.0"?>
<robot name="beacon_$(arg prefix)" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="width"  value="0.08" />
  <xacro:property name="height" value="0.16" />

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find nucobot_description)/map_objects/urdf/beacon.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find nucobot_description)/map_objects/urdf/materials.xacro" />

  <!-- Camera -->
  <link name="beacon_$(arg prefix)_base_link">
    <collision>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${width} ${width} ${height}"/>
      </geometry>
      <material name="$(arg color)"/>
    </visual>

    <inertial>
      <mass value="1e-4" />
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <joint name="beacon_$(arg prefix)_base_to_camera" type="fixed">
    <parent link="beacon_$(arg prefix)_base_link"/>
    <child link="beacon_$(arg prefix)_camera_link"/>
    <origin xyz="${width} ${width/2} ${height}" rpy="0 0.5 0"/>
  </joint>

  <link name="beacon_$(arg prefix)_camera_link">
    <inertial>
      <mass value="1e-6" />
      <origin xyz="0 0 ${height/2}" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
</robot>
